import getCurrentUser from "@/actions/getCurrentUser"
import LoginModal from "@/components/modals/LoginModal"
import RegisterModal from "@/components/modals/RegisterModal"
import Navbar from "@/components/navbar/Navbar"
import ToastProvider from "@/providers/ToastProvider"
import { ThemeProvider } from "@/providers/theme-provider"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Food Ordering",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser()
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header>
            <div className="flex h-12 w-full z-30 flex-row fixed inset-y-0">
              <Navbar currentUser={currentUser} />
            </div>
          </header>
          <RegisterModal />
          <LoginModal />
          <ToastProvider />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
